// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf-o_w6w_rK0WjydvGoqjoTokifF4DETw',
    appId: '1:440087410802:web:08d88041136295e887eaeb',
    messagingSenderId: '440087410802',
    projectId: 'e-commerce-app-7da0b',
    authDomain: 'e-commerce-app-7da0b.firebaseapp.com',
    storageBucket: 'e-commerce-app-7da0b.firebasestorage.app',
    measurementId: 'G-WEDK4XNB06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpCd2LFJkPYXSJPj0MjjheJk-X-1QTE80',
    appId: '1:440087410802:android:502cbf635b4979c487eaeb',
    messagingSenderId: '440087410802',
    projectId: 'e-commerce-app-7da0b',
    storageBucket: 'e-commerce-app-7da0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBULU366OC2ebFECWwe4KjjlUYOyaKK6Go',
    appId: '1:440087410802:ios:b5008b79362c234c87eaeb',
    messagingSenderId: '440087410802',
    projectId: 'e-commerce-app-7da0b',
    storageBucket: 'e-commerce-app-7da0b.firebasestorage.app',
    iosBundleId: 'com.example.anECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBULU366OC2ebFECWwe4KjjlUYOyaKK6Go',
    appId: '1:440087410802:ios:b5008b79362c234c87eaeb',
    messagingSenderId: '440087410802',
    projectId: 'e-commerce-app-7da0b',
    storageBucket: 'e-commerce-app-7da0b.firebasestorage.app',
    iosBundleId: 'com.example.anECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf-o_w6w_rK0WjydvGoqjoTokifF4DETw',
    appId: '1:440087410802:web:b09130febc76cced87eaeb',
    messagingSenderId: '440087410802',
    projectId: 'e-commerce-app-7da0b',
    authDomain: 'e-commerce-app-7da0b.firebaseapp.com',
    storageBucket: 'e-commerce-app-7da0b.firebasestorage.app',
    measurementId: 'G-CHND24XQJ6',
  );
}
